logo_title: 蒙园青Rythem的博客

style: white

favicon: /favicon.ico

menu:
  专利: https://d.wanfangdata.com.cn/patent/CN202411281267.2
  简历: pdf/蒙园青-Android系统工程师-150204199808110916-大连东软信息学院.pdf
  Gitee: https://gitee.com/RythemMeng
  Github: https://github.com/yuanqingrythem

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false